#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 Tenstorrent USA, Inc.
"""Independent verification of an OCA-classic bundle.

For the non-secure-boot Scenario A bundle generated by ./config.yaml, this
script verifies the byte-level invariants from the OCA-classic format contract:

    1. The manifest body starts with the four-byte magic OCAC.
    2. The manifest body is exactly 4096 bytes.
    3. The classic trailer at offset 3168 is four 0xCA bytes.
    4. The 32-byte manifest_hash field at offset 3684 is the SHA-256 of the
       signed region (bytes [0, 3172)).

For signed bundles, uncomment the `verify_signature(...)` call near the bottom
of this file — it does the full independent RSA-3072 PKCS#1 v1.5 + SHA-256
signature verification path.

The offsets below are deliberately written out rather than imported from the
packer: the point of this script is to check the bundle against the format as
documented, independently of the code that produced it.

Usage:
    python verify.py path/to/bundle.bin
"""

from __future__ import annotations

import hashlib
import struct
import sys


MANIFEST_BODY_SIZE = 4096
SIGNED_REGION_END = 3172
TRAILER_OFFSET = 3168
MANIFEST_HASH_OFFSET = 3684
SHA256_SIZE = 32

PUBLIC_KEY_CLASSIC_OFFSET = 2120
PUBLIC_KEY_CLASSIC_SIZE = 532
PUBLIC_KEY_SIZE_OFFSET = 2653       # u16 LE: valid bytes in public_key_classic
SIGNATURE_CLASSIC_OFFSET = 3172
SIGNATURE_SIZE_OFFSET = 2094        # u16 LE: valid bytes in signature_classic

RSA_3072_MODULUS_BYTES = 384


def verify_unsigned(bundle: bytes) -> None:
    body = bundle[:MANIFEST_BODY_SIZE]
    assert len(body) == MANIFEST_BODY_SIZE, (
        f"Expected at least {MANIFEST_BODY_SIZE} bytes for manifest body, "
        f"got {len(bundle)}"
    )
    assert body[0:4] == b"OCAC", f"Expected OCAC magic at offset 0, got {body[0:4]!r}"
    assert body[TRAILER_OFFSET : TRAILER_OFFSET + 4] == b"\xCA\xCA\xCA\xCA", (
        f"Expected classic trailer 0xCA*4 at offset {TRAILER_OFFSET}, "
        f"got {body[TRAILER_OFFSET : TRAILER_OFFSET + 4]!r}"
    )

    signed_region = body[:SIGNED_REGION_END]
    embedded_hash = body[MANIFEST_HASH_OFFSET : MANIFEST_HASH_OFFSET + SHA256_SIZE]
    expected_hash = hashlib.sha256(signed_region).digest()
    assert embedded_hash == expected_hash, (
        "manifest_hash mismatch: "
        f"embedded={embedded_hash.hex()} expected={expected_hash.hex()}"
    )

    print("OK: OCA magic, length, trailer, and manifest_hash all verified.")


def verify_signature(bundle: bytes) -> None:
    """RSA-3072 PKCS#1 v1.5 + SHA-256 path for Scenario B (signed bundle).

    Independent of the project — uses only `cryptography` primitives, which is
    the same primitive `manifest_signing.py` uses to sign, so this is a
    genuine independent check.
    """
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.asymmetric import padding, rsa

    body = bundle[:MANIFEST_BODY_SIZE]
    signed_region = body[:SIGNED_REGION_END]

    # Both values are sliced by their companion size field. That is what those
    # fields are for: each blob sits in a field sized for the largest supported
    # value and zero-padded beyond, and trimming trailing 0x00 to find the end
    # is ambiguous — a modulus or a signature may legitimately end in a zero byte.
    key_size = struct.unpack_from("<H", body, PUBLIC_KEY_SIZE_OFFSET)[0]
    sig_size = struct.unpack_from("<H", body, SIGNATURE_SIZE_OFFSET)[0]
    key_bytes = body[PUBLIC_KEY_CLASSIC_OFFSET : PUBLIC_KEY_CLASSIC_OFFSET + key_size]
    signature = body[SIGNATURE_CLASSIC_OFFSET : SIGNATURE_CLASSIC_OFFSET + sig_size]

    # Raw (encoding 0x02) RSA public key: big-endian modulus followed by a
    # 4-byte big-endian public exponent.
    assert key_size == RSA_3072_MODULUS_BYTES + 4, (
        f"Expected a {RSA_3072_MODULUS_BYTES + 4}-byte raw RSA-3072 key, got {key_size}"
    )
    modulus = int.from_bytes(key_bytes[:RSA_3072_MODULUS_BYTES], "big")
    exponent = int.from_bytes(key_bytes[RSA_3072_MODULUS_BYTES:], "big")
    pk = rsa.RSAPublicNumbers(exponent, modulus).public_key()

    pk.verify(signature, signed_region, padding.PKCS1v15(), hashes.SHA256())
    print("OK: RSA-3072 signature verified against embedded public key.")


def main() -> int:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <bundle.bin>", file=sys.stderr)
        return 2

    with open(sys.argv[1], "rb") as fh:
        bundle = fh.read()

    verify_unsigned(bundle)
    # For Scenario B (signed) bundles, also call:
    #     verify_signature(bundle)
    return 0


if __name__ == "__main__":
    sys.exit(main())
